### ISSUE TITLE
Error: Could not locate the bindings file on RaspberryPi

### ISSUE THREAD

**Issue by ceremcem** [Cloud-Automation/node-net-reconnect#3] opened 2018-04-05 10:20 UTC
Here is the output of the error: 

```
Error: Could not locate the bindings file. Tried:
 → /home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/build/binding.node
 → /home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/build/Debug/binding.node
 → /home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/build/Release/binding.node
 → /home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/out/Debug/binding.node
 → /home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/Debug/binding.node
 → /home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/out/Release/binding.node
 → /home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/Release/binding.node
 → /home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/build/default/binding.node
 → /home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/compiled/8.1.4/linux/arm/binding.n
ode
    at bindings (/home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/bindings/bindings.js:88:
9)
    at Object.<anonymous> (/home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/ref/lib/ref.js
:5:47)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/aea/apps/therm-demo/dcs/transports/tcp/node_modules/net-keepalive/
lib/index.js:4:11)
```
------------------------------------
------------------------------------
# Solution 
As stated [here](https://github.com/JamesBarwell/rpi-gpio.js/issues/36): 

```
npm rebuild
```

**Comment by stefanpoeter** [comment] 2018-04-13 06:44
That doesn't seem specific for this module but a general npm issue, don't you think?

**Comment by ceremcem** [comment] 2018-04-14 15:29
That's right. The purpose I put the issue here is that if someone faces with such an issue, he or she can find the answer more quickly. 

As a workaround, `npm rebuild` might be added as a [postinstall](https://docs.npmjs.com/misc/scripts) script. I may add this workaround and create a PR when I encounter this problem again. 

It's up to you to keep this issue opened or closed.

**Comment by stefanpoeter** [comment] 2018-04-16 07:44
Thanks, I'll close it. People will find it even when the issue is closed. Thanks for your commitment.

**Closed as completed by stefanpoeter** 2018-04-16 07:44 UTC
